FROM ubuntu:latest
MAINTAINER Gopi Subramanian "gopi.subramanian@gmail.com"
RUN apt-get update -y
RUN apt-get install -y libgtk2.0-dev
RUN apt-get install -y python3 python3-pip python3-dev build-essential cmake
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
COPY . /Akshi
WORKDIR /Akshi
RUN pip3 install -r requirements.txt

